# 博客静态部署配置
# 用途：使用Nginx提供Astro构建的静态文件服务

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: blog_nginx
    # 端口映射：主机的8090端口 → 容器的80端口
    ports:
      - "8090:80"
    volumes:
      # docker-compose.yml 在 ~/blog/code/ 目录下
      # 相对路径从此目录开始计算
      - ./lingLong/dist:/usr/share/nginx/html:ro
    # 资源限制：适配树莓派4 (2GB内存)
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped

# 网络配置（可选，Docker Compose会自动创建）
networks:
  default:
    name: blog_network
