# 博客集成部署环境配置
# 用途：在PC上模拟树莓派生产环境的完整部署架构

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: sim_backend
    # 启动命令：开启热重载支持实时开发
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # 卷挂载
    volumes:
      - ./backend/app:/code/app          # 后端代码
      - ./backend/data:/code/data        # SQLite数据库
      - ./yukina:/code/yukina            # Astro项目（后端操作Markdown文件）
      - /code/yukina/node_modules        # 匿名卷：防止宿主机node_modules覆盖容器内的Linux版本
    # 环境变量
    environment:
      - ENVIRONMENT=production           # 环境标识
      - ASTRO_CONTENT_PATH=/code/yukina/src/contents/posts
      - ASTRO_PROJECT_PATH=/code/yukina
    # 注意：不对外暴露端口，只通过nginx访问

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: sim_nginx
    # 端口映射：PC的8080端口 → 容器的80端口
    ports:
      - "8080:80"
    volumes:
      - ./yukina/dist:/usr/share/nginx/html
    # 依赖关系：等待backend启动后再启动nginx
    depends_on:
      - backend

# 网络配置（可选，Docker Compose会自动创建）
networks:
  default:
    name: blog_network