version: '3.8'
services:
  backend:
    # 告诉 Docker Compose 使用当前目录下的 Dockerfile 来构建镜像
    build: .
    # 命名容器，方便管理
    container_name: blog_backend_dev
    # 端口映射：将您 PC 的 8000 端口映射到容器的 8000 端口
    ports:
      - "8000:8000"
    volumes:
      # 挂载您的源代码目录：
      # PC上的 ./app 目录 <--> 容器内的 /code/app 目录
      # 作用：实现代码热重载
      - ./app:/code/app
      - ./data:/code/data
      # 挂载前端的posts目录，让后端能读取markdown文件
      - ../yukina/src/contents/posts:/code/yukina/src/contents/posts
    # 覆盖 Dockerfile 中的 CMD，使用 --reload 参数开启热重载
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload