version: '3.8'
services:
  backend:
    # 告诉 Docker Compose 使用当前目录下的 Dockerfile 来构建镜像
    # Tell Docker Compose to use the Dockerfile in the current directory to build the image
    build: .
    # 命名容器 -- naming container 
    container_name: blog_backend_dev
    # 端口映射：将 PC 的 8000 端口映射到容器的 8000 端口
    # Port mapping: Map port 8000 of the PC to port 8000 of the container
    ports:
      - "8000:8000"
    volumes:
      # 挂载源代码目录：
      # PC上的 ./app 目录 <--> 容器内的 /code/app 目录
      # Mount the source code directory:
      # ./app directory on the PC <--> /code/app directory inside the container
      - ./app:/code/app
      - ./data:/code/data
      # 挂载前端的posts目录，让后端能读取markdown文件
      # Mount the posts directory on the front end so that the back end can read the markdown file
      - ../lingLong/src/contents/posts:/code/lingLong/src/contents/posts
    # 覆盖 Dockerfile 中的 CMD，使用 --reload 参数开启热重载
    # Override the CMD in the Dockerfile and use the --reload parameter to enable hot reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload